blank_issues_enabled: true
contact_links:
  - name: "Pf2ools community Discord server"
    url: "https://discord.gg/2hzNxErtVu"
    about: "Please see the #brew-conversion channel for *all* homebrew issues and requests. We're also available just to chat!"
