name: Unconverted source
description: Report a Paizo source we haven't converted yet
labels: "📝 Unconverted source"
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: "Please enter the source's full, official title as the issue's title above (e.g. \"Lost Omens: Divine Mysteries\")."
  - type: checkboxes
    id: checks
    attributes:
      label: Before we continue...
      options:
        - label: This source isn't already on the [conversion tracker](https://github.com/orgs/Pf2ools/projects/1).
          required: true
        - label: This source has been released and is publicly available.
          required: true
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Where can we find it?
      description: Include a source for that source—a storepage link or similar!
      placeholder: https://paizo.com/products/btq02ej2?Pathfinder-Player-Core
    validations:
      required: true
  - type: dropdown
    id: info
    attributes:
      label: What type of source is it?
      description: Pick the one that best applies.
      options:
        - Sourcebook (e.g. Call of the Wild)
        - Setting book (e.g. Tian Xia World Guide, Lost Omens: Divine Mysteries)
        - Large adventure (e.g. Wardens of Wildwood \#1: Pactbreaker)
        - Small adventure (e.g. _Rusthenge_)
        - Pathfinder Society playbook
        - Blog post, comic, or some other small supplement
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### Thanks for letting us know!\nPlease drop by our [Discord server](https://discord.gg/2hzNxErtVu) if you'd like to help convert any amount of this source."
